### ISSUE TITLE
Limpar da base as colunas descartáveis já identificadas

### ISSUE THREAD

**Issue by VanSharine** [atlantico-academy/analysus#11]

**Comment by JosueSantos** [comment]
Arquivo | Tamanho Original | Linhas | Colunas | Tamanho Final | Colunas Relevantes | Arquivo Limpo
-- | -- | -- | -- | -- | -- | --
df_internacoes.csv | 1,59 GB | 2.956.343 | 113 | 1,32 GB | 49 | internacoes.csv
internacoes.csv | 1,32 GB | 2.956.343 | 49
internacoes_fortaleza.csv | 404,9 MB | 867.020 | 49

- Internacoes.csv (https://drive.google.com/file/d/1-5EJi6zieQY9RSMpzBUj_pYjAH0C0xJW/view?usp=sharing)
- Internacoes_Fortaleza.csv (https://drive.google.com/file/d/1-COBYNnFldb7NkW2SiHbJV51VWTUHB4G/view?usp=sharing)

Bases Mescladas
- mu_ibge - Municipios IBGE
- cid_10 - Descrições CID_10
- car_int - Caráter da internação
- cobranca - Motivo de saída/permanência
- cod_idade - Unidade de medida da idade
- complex - Complexidade
- espec - Especialidade do leito
- financ - Tipo de financiamento
- gestao - Indica o tipo de gestão do hospital
- ident - Identificação do tipo da AIH
- instru - Grau de instrução do paciente
- marca_uti - Indica qual o tipo de UTI utilizada pelo paciente
- nacional - Nacionalidade do paciente
- nat_jur - Natureza jurídica do estabelecimento, conforme a Comissão Nacional de Classificação - CONCLA
- raca_cor - Raça/cor do paciente
- regct - Regra contratual
- Sexo do paciente

https://github.com/atlantico-academy/analysus/blob/main/notebooks/clean_data.ipynb
Realizado a busca de Bases Relacionadas para a complementação dos dados.

https://github.com/atlantico-academy/analysus/blob/main/notebooks/fortaleza.ipynb
Mapeado cada uma das colunas com suas descrições e observações
