### ISSUE TITLE
Descrição do projeto Github

### ISSUE THREAD

**Issue by VanSharine** [atlantico-academy/analysus#12]

**Comment by omadson** [comment]
O que foi feito sobre essa issue? Quando vai ser iniciada?

**Comment by JosueSantos** [comment]
https://docs.google.com/document/d/1iqWKE0ZUlqfugccd1yqy-YO1iIcCPPtMZbyGs9qFkvQ/edit?usp=sharing

depois de finalizado, pode-se colocar este documento como README do projeto
