### ISSUE TITLE
Análise exploratória dos dados

### ISSUE THREAD

**Issue by VanSharine** [atlantico-academy/analysus#8]

**Comment by JosueSantos** [comment]
https://github.com/atlantico-academy/analysus/blob/main/notebooks/clean_data.ipynb
Realizado a busca de Bases Relacionadas para a complementação dos dados.

https://github.com/atlantico-academy/analysus/blob/main/notebooks/fortaleza.ipynb
Mapeado cada uma das colunas com suas descrições e observações
